### ISSUE TITLE
--password flag doesn't work

### ISSUE THREAD

**Issue by mbryzek** [mbryzek/schema-evolution-manager#37]
[ec2-user@ip-10-20-2-47 harmonization-postgresql]$ sem-apply --user api --host xxx --name harmonizationdb --password
Please enter the database user password[xxxxx]
/usr/local/lib/schema-evolution-manager-0.9.26/lib/schema-evolution-manager/library.rb:106:in `block in write_to_temp_file': no block given (yield) (LocalJumpError)
    from /usr/local/lib/schema-evolution-manager-0.9.26/lib/schema-evolution-manager/library.rb:88:in`with_temp_file'
    from /usr/local/lib/schema-evolution-manager-0.9.26/lib/schema-evolution-manager/library.rb:102:in `write_to_temp_file'
    from /usr/local/lib/schema-evolution-manager-0.9.26/lib/schema-evolution-manager/db.rb:14:in`initialize'
    from /usr/local/lib/schema-evolution-manager-0.9.26/lib/schema-evolution-manager/db.rb:105:in `new'
    from /usr/local/lib/schema-evolution-manager-0.9.26/lib/schema-evolution-manager/db.rb:105:in`from_args'
    from /usr/local/bin/sem-apply:26:in `<main>'

**Comment by mbryzek** [comment]
This has been fixed
